### ISSUE TITLE
S.valid calc

### ISSUE THREAD

**Issue by antshi** [MGallow/CVglasso#1]
Hey MGallow,

thank you for the CVglasso package. It eases the pain of building a CV. :)
Still, a question for the following code snippet

            leave.out = ind[(1 + floor((k - 1) * n/K)):floor(k * 
                n/K)]
            X.train = X[-leave.out, , drop = FALSE]
            X_bar = apply(X.train, 2, mean)
            X.train = scale(X.train, center = X_bar, scale = FALSE)
            
            # validation set
            X.valid = X[leave.out, , drop = FALSE]
            X.valid = scale(X.valid, center = X_bar, scale = FALSE)
            n = nrow(X.valid)
            
            # sample covariances
            S.train = crossprod(X.train)/(dim(X.train)[1])
            S.valid = crossprod(X.valid)/(dim(X.valid)[1])

why do you center the X.valid around the mean of the X.train?

I would be happy to hear from you.

Best wishes
antshi

**Comment by MGallow** [comment]
Thanks for the comment @antshi . X.valid is used to calculate the sample covariance matrix of the validation set (S.valid) for the validation likelihood criteria in our cross validation. Because of this, we should be concerned about leaking information from the validation set and biasing our estimates -- centering by the mean of X.train instead of the mean of X.valid ensures that we do not.

Another simple example: suppose that X.valid consists of only one observation. Then centering X.valid by the mean of X.valid will always result in S.valid = 0 and renders our validation likelihood criteria useless.

**Comment by antshi** [comment]
thank you, @MGallow for the explanations. This does not make much sense for stocks data though, so I forked it. Best wish
